### ISSUE TITLE
NPM Package?

### ISSUE THREAD

**Issue by yumyo** [gremo/react-directus#81]
Hi, thank you for working on this. Is there an ETA for the NPN package?

**Comment by gremo** [comment]
Hi, thanks for the interest in this library! I didn't not published this yet because Directus is still in 9.0.0-rc.95. I'll probably publish it when 9 is final!

**Comment by oachoor** [comment]
@gremo Thanks for this too! and Directus is now released 🎉   
https://github.com/directus/directus/releases/tag/v9.0.0

**Comment by matthiaskrieft** [comment]
@gremo thx as well from my side. Btw, we're using + testing it already in our product.

Would be great to include it from npm directly instead of cloning it from github, so really looking forward to the published version ;-)

**Comment by gremo** [comment]
Glad to know that!

Before publishing, I need some help. I can't use Travis CI for testing and PR automerging because of the rate/builds limits. It happened on another project too, and someone pushed a github workflow. Here is it: https://github.com/gremo/nest-winston/blob/master/.github/workflows/test-on-push.yml

Are you @oachoor or @matthiaskrieft able to adapt it for this project? Do you consider this project stable/tested to be public and 1.0?

**Comment by gremo** [comment]
Now on npm 😃 let me know if it's all ok, thank you for helping!
